services:
  # Base de donn√©es PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: identity-provider-db
    environment:
      POSTGRES_USER: cloudmap
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: cloudmap_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # API Identity Provider
  identity-provider:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: identity-provider-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=73eec47c44d248d5efc6aa4fe836f95b3a504c1d
      - JWT_EXPIRES_IN=24h
      - MAX_LOGIN_ATTEMPTS=3
      - LOCK_DURATION_MINUTES=15
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=cloudmap
      - DB_PASSWORD=password123
      - DB_NAME=cloudmap_db
      - FIREBASE_PROJECT_ID=signalementroutier-1b496
      - FIREBASE_SERVICE_ACCOUNT_PATH=./config/firebase-service-account.json
      - FIREBASE_SIGNALEMENTS_COLLECTION=signalements
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
